service: units

provider:
  name: aws
  stage: development
  region: ap-southeast-2
 
functions:
  unitsGet:
    handler: server.unitsGet
    events:
      - http:
          path: units
          method: get
          cors: true
  unitCreate:
    handler: server.unitCreate
    events:
      - http:
          path: unit
          method: post
          cors: true
  unitDelete:
    handler: server.unitDelete
    events:
      - http:
          path: delete-unit
          method: post
          cors: true
