service: units

provider:
  name: aws
  stage: development
  region: ap-southeast-2
 
functions:
  unitsGet:
    handler: server.unitsGet
    events:
      - httpApi: 'GET /units'
  unitCreate:
    handler: server.unitCreate
    events:
      - httpApi: 'POST /unit'
  unitDelete:
    handler: server.unitDelete
    events:
      - httpApi: 'POST /delete-unit'
